USE MyBelfast;

INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '【打卡广东高质量】从航天卫星到手机电脑，上天遁地都与它相关', 2307, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '【打卡广东高质量】来，看看你的“经济名片”什么样', 1172, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '好消息！事关大学生毕业证发放，教育部发新通知', 2689, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '外交部：将对参与此次售台武器的美国企业实施制裁', 1230, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '国家邮政局：上半年快递业务量达277.6亿件 同比增长25.7%', 355, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '浙江生产总值从1949年的15亿元跃升到2018年的5.6万亿元 改革开放再出发', 2345, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '一张“固执”的反对票，挽救了中央红军', 2279, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '破解内生动力不足难题，罗家山村“志智双扶”精准发力 心热了，劲头就足了', 544, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '上半年进出口总值增长3.9% 外贸结构优化动力转换加快', 270, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '人民日报评论员：牵住“责任制”这个牛鼻子', 1228, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '“购物车”有力拉动“基本盘”', 1853, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '中纪委机关报：不能在喝彩声中丧失革命精神和斗志', 1497, '20190713', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '今年长江1号洪水即将形成 三峡水库控制下泄流量', 69, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '扶贫办：加强廉洁扶贫阳光扶贫 严查违纪违法行为', 2164, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '我国多种资助方式实现高校经济困难学生入学“三不愁”', 2275, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '外交部：强烈敦促加方立即释放孟晚舟', 1309, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '报告：“僵尸”型社会组织广泛清理 监管从严成政策方向', 865, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '做妇女信得过靠得住离不开的娘家人 全国妇联成立70周年座谈会在京举行', 1470, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '凝聚妇女力量 全国妇联成立70周年纪念展在京开幕', 1577, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '外交部发言人：反对美方利用宗教问题干涉别国内政', 689, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '国家防总、应急管理部派出5个工作组协助指导地方开展抗洪抢险救灾', 1696, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '新华网评：要切实践行新时代好干部标准', 1092, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '辛识平：下足“绣花功夫”决胜脱贫攻坚', 959, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '结合实际学深悟透 聚焦问题真抓实干——新疆、新疆生产建设兵团、西藏扎实深入推进主题教育', 1441, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '中方将对参与售台武器的美国企业实施制裁', 1332, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '五部门部署做好当前形势下高校毕业生就业创业工作', 1109, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '美考虑缓解对朝制裁 外交部：呼吁有关各方秉持建设性态度', 2394, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '外交部回应美涉南海仲裁案裁决三周年表态：双重标准、霸权逻辑、虚伪丑陋', 1290, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '中国成功申办2022年世界新闻教育大会', 1242, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '评蔡英文“过境”美国 国台办：挟洋自重、错判形势', 2278, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '报告：中国社会组织超81万个 监管从严成政策主基调', 2068, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '壮丽70年 奋斗新时代·脱贫攻坚乡村行：搬出深山 奔向新生活', 2897, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '山东大学：学校将对“学伴”项目进行全面评估 认真总结反思', 2039, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '炫彩60秒·綦江篇', 2891, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '书记晒文旅·綦江篇', 2476, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '贺龙元帅称赞 綦江是个好地方', 2600, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '【打卡广东高质量】印象东莞之青年：“我喜欢这里的创业环境”', 2895, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '当志愿服务遇上温暖童年 “守护童年”大学生暑期牵手共成长行动启动', 716, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '服装定制普通人也穿得起！AI裁缝30秒打造专属新衣', 2811, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '特色品牌助推精准扶贫 首届“一乡一品”产业设计大赛启动', 899, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '急救小课堂 儿童座椅安装吉尼斯 北京妇儿公益服务博览会有趣有料！', 781, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '创新“基层党建+”，“德孝文化”进乡村，方城县清河镇——以文化人促乡村振兴', 2452, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '农业农村部：今年农村“厕所革命”整村奖补将惠及千万农户', 731, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '教育部：职业院校奖助学金向艰苦专业、贫困地区倾斜', 1985, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '北京：毕业生见习期可申请每月2200元补贴', 956, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '留得住村医，贫困人口基本医疗才有保障', 303, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '蔡玉亭：1095天，“毛巾哥”这样炼成', 1303, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '娄山关战斗：红军长征以来的第一场大胜仗', 112, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '“千校万岗”就业精准帮扶首场县域专项招聘会走进河南封丘 两千个就业岗位送到村民家门口', 1737, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '上海美颜：数据决定美', 2049, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '交通运输部、人社部、应急管理部、国家能源局扎实开展主题教育——奔着问题去 能改马上改', 614, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '上半年我国实际使用外资增长7.2% 新设外资企业超两万家', 2873, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '搬出深山 奔向新生活', 210, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '商务部：中方不会打压歧视外资企业 将坚决保护外企合法权益', 787, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '外交部发言人：反对借涉疆问题干涉中国内政', 1718, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '守大堤、防山洪内涝 湘赣黔备战持续性强降雨', 478, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '香港同胞庆祝国庆筹委会成立 两场演出欢度国庆', 500, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '司法部：城乡基本公共法律服务资源将实行均衡配置', 2568, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '商务部：中美经贸团队正在就下一步具体安排保持沟通', 2712, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '香港旅游业界人士：香港高铁直达内地站点增加将拉动香港旅游业', 136, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '“记者再走长征路”采访团在贵州遵义与“时代楷模”畅谈长征精神', 350, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '海外演训场，走来一群中国卫生士官', 1851, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '多国军官观摩中德“联合救援-2019”卫勤实兵联合演习', 196, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '团十八届中央书记处举行第八次集体学习', 61, '20190712', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '《晋绥日报》精神永存 红色晋绥薪火相传<br>——吕梁学院师生一行做客山西省晋绥文化教育发展基金会', 735, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '【看长江之变】“共舞长江经济带——看长江之变”网络主题活动在重庆启动', 1525, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '中国经济在高质量发展的大道上扎实前行', 2125, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '安徽庐江乐华村：靛青蓝莓高高挂，美了乡村，富了农家', 1388, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '山西隰县：一个贫困县的电商“扶贫经”', 2900, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '雄关漫道真如铁——探访娄山关', 822, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '外交部发言人：反对借涉疆问题干涉中国内政', 549, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '中欧圆桌会议第十七次会议在上海举办', 2041, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '“南海救116”轮接上32名遇险渔民返回琼岛', 500, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '国家医保局约谈三省区负责人 要求彻底整改医保欠费问题', 1572, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '我国2018年资助各类家庭经济困难学生近1亿人次', 2160, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '精致又有深意！来看北大新版“大学堂”牌匾录取通知书', 1499, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '浙江省人民政府同意设立宁波前湾新区 规划面积604平方公里', 1989, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '天津检察机关依法对穆怀国涉嫌贪污、受贿案提起公诉', 2179, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '国防部新闻发言人吴谦就美国售台武器发表谈话', 2475, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '“大湾区带给我们归属感和信任感”——澳门青年粤港澳大湾区实习记', 46, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '暴风骤雨中，他们奋战在前——江西党员干部抗洪抢险素描', 495, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '商务部：不可靠实体清单制度正履行程序 近期将发布', 969, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '“中国强大，人民幸福，烈士的鲜血没有白流”——专访渣滓洞、白公馆脱险志士', 2749, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '水利部发布洪水黄色预警 10省区须注意防范', 1523, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '国防部回应美国售台武器：中国军队强烈不满、坚决反对', 93, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '非你莫属！看广州南沙实力优待高端人才', 2834, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '中国自主建造的“雪龙2”号极地科学考察破冰船交付使用', 2720, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '快递业黑名单制度呼之欲出 哪些企业和个人或上榜？', 2197, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '商务部回应美取消对110种中国商品加征关税', 1034, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '商务部：中美经贸团队正在就下一步具体安排保持沟通', 1644, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '教育部15日将全面开通高校学生资助热线电话服务', 149, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '商务部：中国并没有出现大规模的外资撤离情况', 965, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '大熊猫“珠珠”生下龙凤胎 陕西圈养大熊猫达23只', 1940, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '外交部、中联部扎实开展“不忘初心、牢记使命”主题教育', 2223, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '“倾力奉献，人生就不平凡”（人民满意的公务员）', 994, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '新华网评：在自我革命中坚守初心使命', 1733, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '深化教育教学改革 全面发展素质教育', 1492, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '贵阳市委书记：教师涉嫌猥亵学生事件影响恶劣教训深刻', 1887, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '山东枣庄成立问题水泥事件调查组 涉事企业被责令停产', 2655, '20190711', '中国青年网', '/blank');
INSERT INTO MyBelfast.NEWS (  title, hits, outTime, tag, url) VALUES ( '【边疆党旗红】搭建社区“大党委” 新疆社区服务模式实现新突破', 2555, '20190711', '中国青年网', '/blank');